### ISSUE TITLE
More options to templatize

### ISSUE THREAD

**Issue by Raynbda** [LesFerch/FolderViewPainter#2]
Is it possible to make folderviewpainter remember if preview pane or details pane is open, or hidden files are shown or if navigation pane is enabled, or certain settings in options are on/off...?

**Comment by LesFerch** [comment]
Yes, but keep in mind that those are all _global_ settings. They cannot be applied to a specific folder.

I could add a new option (checkbox) to include global settings in exported views. When imported, your global Explorer settings would be updated along with the folder view. I'll put that on the To Do.

**Comment by Raynbda** [comment]
Maybe you could add a reset to windows default options or reset to user defined options to fix that issue. You could also maybe make an automation to automatically reset to default view once you close the folder that you applied the template to.

**Comment by LesFerch** [comment]
I have to be very careful how such an option is presented to avoid confusion. It's very important when dealing with settings that apply globally. A user may not want to go back to Windows defaults. And I have to be careful about how such a feature is labelled.  Things can't be wordy since my apps are always multilingual. I'll have to give this a good long think. Thanks for the suggestions.

**Comment by LesFerch** [comment]
I can't do anything on window close, as that would require spawning a watcher process that applies settings when the folder is closed. That would be difficult to program, add overhead, and be error prone.

What I can do is add a global Explorer settings checkbox to Export and add a method to automatically apply the global Explorer settings of your choice whenever "Reset View" is selected. I'm planning to implement that simply by having the "Reset View" function apply a reg file named `!ResetView.ini` (if it exists). I'm also going to allow FolderViewPainter to work from a protected location, such as Program Files, by having the saved views go to the user's AppData folder whenever the executable is not in a writable location. I'll also create a nice installer for the app, but portable installation will still be supported.

**Comment by LesFerch** [comment]
Please test [version 1.3.0](https://wormhole.app/pYmM9#RFuqtnx_1LRei-MT1mkotA). I still have to update the readme. You should see the checkbox in Export and another checkbox in Options to include or not include Explorer settings in "Reset View". You should see the file `!ResetView.ini` created or removed when that box is checked or unchecked.

**Comment by Raynbda** [comment]
Nice! I’ll test it as soon as I can, and if there’s anything to note, I’ll let you know. Thanks for the update!

**Comment by Raynbda** [comment]
It seems that only the preview pane and details pane are working for now, other settings from "options" menu aren’t getting saved. Ideally, I’d like to see exactly which features are being saved rather than just having a global "Save Explorer options" checkbox, and the ability to toggle them off.

**Comment by LesFerch** [comment]
The keys that are saved will be noted in the readme. You can see them by selecting `Manage` and looking at the file `!ResetView.ini` or any Reg file where you've checked the option to include settings.

It currently captures `Explorer\Modules\GlobalSettings` (where the preview/details pane settings are stored) and `Explorer\Advanced` (where all the items from Properties > View are saved). I don't think it would be appropriate to capture the settings from the General or Search tabs.

If you want it more granular, you can to edit the files in the `SavedViews` folder. I'm not going to build out a whole replication of the Explorer's properties dialog.

**Comment by LesFerch** [comment]
I'd like to post version 1.3.0. Did you complete your testing?

**Comment by Raynbda** [comment]
Yes
